#    Carpenter
#    A cross-platform dotnet (.NET) build process helper.
#
#    Copyright © 2015-2019 Nosnitor Corporation, All rights reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

# SPDX-License-Identifier: MIT

#
# Pipeline definition for Azure Pipelines.
#

variables:
    # The VM Image to use for build steps.
    "Carpenter.Build.VMImage": "ubuntu-latest"

    # The name of the solution, as used in the Visual Studio .sln file.
    "Carpenter.SolutionName": 'Carpenter'

    # The Organization this project is under in SonarCloud.
    "Carpenter.SonarCloud.Organization": 'nosnitor'

    # The Project Key for this project in SonarCloud.
    "Carpenter.SonarCloud.ProjectKey": 'Nosnitor_Carpenter'

    # The name of the Azure DevOps service connection.
    "Carpenter.SonarCloud.ServiceConnection": 'SonarCloudAnalysis1'

# Default name for the build, prior to build versioning
# $(Build.BuildId) is the default value used when YAML cannot be parsed
name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true
  branches:
    include:
    - master

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

  - repository: carpenterAzurePipelines
    type: github
    name: Nosnitor/Carpenter.AzurePipelines
    endpoint: Nosnitor

stages:
- template: templates/stage/carpenter-default.yml@carpenterAzurePipelines
  parameters:
    solutionName: '$(Carpenter.SolutionName)'
    sonarCloudOrganization: '$(Carpenter.SonarCloud.Organization)'
    sonarCloudProjectKey: '$(Carpenter.SonarCloud.ProjectKey)'
    sonarCloudServiceConnection: '$(Carpenter.SonarCloud.ServiceConnection)'
    vmImage: 'ubuntu-latest'
